version: "3.8"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume: